fetch_next_game_task:
  description: >
    Find and report the next scheduled game of the team specified below:

    Team: {team_name}

    The output should include:
    - Opponent's name
    - Date and time of the match
    - Venue

    Your final output MUST be a short paragraph summarizing the information.
    favour la liga.com result and we are at date {current_date}.
  expected_output: >
    The next game for {team_name} is against [Opponent Name] on [Date] at [Time],
    to be held at [Venue].
  agent: sports_analyst

write_sports_article_task:
  description: >
    Write a sports article based on the latest sports news and events.
    Your article should be engaging and insightful, providing a fresh perspective
    on the sports events of the day.
  expected_output: >
    A well-written sports article that captures the essence of the latest sports
    news and events, providing a unique perspective on the subject matter.
  output_file: >
   sports_article.txt  
  agent: sports_writer  